### ISSUE TITLE
Virtual inheritance and virtual base classes

### ISSUE THREAD

**Issue by 0xBEEEF** [cmu-sei/pharos#130]
[Here](https://github.com/0xBEEEF/VisualCppTests/tree/master/InheritanceTest2/ConsoleApplication1) is an example based on another example. It has been separated out to simplify the analysis. It was compiled again in Visual Studio 2019.

The example contains a medium-deep nesting of classes and a lot of virtual inheritance. So it's an ideal example to try out the analysis possibilities.

After compiling in release mode the following output is visible. Looks good from the idea at first. But (unfortunately) some structures were overlooked, which were included in the program.

```
OPTI[INFO ]: Analyzing executable: /dir/InheritanceTest2/ConsoleApplication1.exe
OPTI[INFO ]: OOAnalyzer version 1.0.
OPTI[INFO ]: ROSE stock partitioning took 6.06136 seconds.
OPTI[INFO ]: Partitioned 7351 bytes, 2187 instructions, 531 basic blocks, 0 data blocks and 142 functions.
OPTI[INFO ]: Pharos function partitioning took 8.21962 seconds.
OPTI[INFO ]: Partitioned 10752 bytes, 2895 instructions, 742 basic blocks, 42 data blocks and 235 functions.
APID[WARN ]: API database could not find function terminate in api-ms-win-crt-runtime-l1-1-0
OOAN[WARN ]: No stack delta information for: api-ms-win-crt-runtime-l1-1-0.dll:terminate
OOAN[ERROR]: No delete() methods were found.  Object analysis may be impaired.
OPTI[INFO ]: Function analysis complete, analyzed 176 functions in 7.03039 seconds.
OOAN[WARN ]: Missing this-pointer usage for new() call at 401951: call      40271C
OOAN[WARN ]: Missing this-pointer usage for new() call at 40198B: call      40271C
OOAN[WARN ]: Missing this-pointer usage for new() call at 401A05: call      40271C
OOAN[WARN ]: Missing this-pointer usage for new() call at 401A7F: call      40271C
OOAN[WARN ]: Missing this-pointer usage for new() call at 401B63: call      40271C
OOAN[WARN ]: Missing this-pointer usage for new() call at 401BB7: call      40271C
OOAN[WARN ]: Missing this-pointer usage for new() call at 401C31: call      40271C
OOAN[WARN ]: Missing this-pointer usage for new() call at 401D1B: call      40271C
OPTI[INFO ]: OOAnalyzer analysis complete, found: 17 classes, 52 methods, 0 virtual calls, and 71 usage instructions.
OPTI[INFO ]: Successfully exported to JSON file '/dir/InheritanceTest2/test.json'.
OPTI[INFO ]: OOAnalyzer analysis complete.
```

Let's take a closer look at the "H::access" function in this example. This function is based internally on several VBTables and also VFTables. You can see this in the intermediate output of Visual Studio.

```
 class H	size(44):
  	+---
   0	| {vbptr}
   4	| h_data
  	+---
  8	| (vtordisp for vbase E)
  	+--- (virtual base E)
  12	| +--- (base class AbstractA)
  12	| | {vfptr}
  16	| | abstract_a_data
  	| +---
  20	| e_data
  	+---
  24	| (vtordisp for vbase AbstractA)
  	+--- (virtual base AbstractA)
  28	| {vfptr}
  32	| abstract_a_data
  	+---
  	+--- (virtual base F)
  36	| {vbptr}
  40	| f_data
  	+---
  H::$vbtable@H@:
   0	| 0
   1	| 12 (Hd(H+0)E)
   2	| 28 (Hd(H+0)AbstractA)
   3	| 36 (Hd(H+0)F)
  H::$vftable@E@:
  	| -12
   0	| &(vtordisp) H::{dtor}
   1	| &E::abstract_a_foo
   2	| &(vtordisp) H::access
  H::$vftable@F@:
  	| -28
   0	| &(vtordisp) thunk: this-=16; goto H::{dtor}
   1	| &(vtordispex) thunk: this+=20; goto F::abstract_a_foo
   2	| &(vtordisp) thunk: this-=16; goto H::access
  H::$vbtable@F@:
   0	| 0
   1	| -8 (Hd(F+0)AbstractA)
  H::{dtor} this adjustor: 12
  H::access this adjustor: 12
  H::__delDtor this adjustor: 12
  H::__vecDelDtor this adjustor: 12
  vbi:	   class  offset o.vbptr  o.vbte fVtorDisp
                 E      12       0       4 1
         AbstractA      28       0       8 1
                 F      36       0      12 0
```

So this is the actual output of the class in the created file. It is quite interesting. You see there are several VFTables but also a lot of VBTables.

But here I currently have a problem. Apparently the resolution of all these dependencies doesn't work. Mostly there is only the first VFTable. There is no obvious trace of VBTables. I find this totally confusing.

I have not included the complete analysis of the H::access function now, because that would be much too extensive. But from my point of view it would be a good starting point, because here everything comes together and the complexity is quite visible. It's probably better if you try to recreate it all by yourself.

**Comment by 0xBEEEF** [comment]
All classes and how they were implemented in assembler according to Visual C++. These are in principle the structures, which should be found by the analysis.

```
  class AbstractA	size(8):
  	+---
   0	| {vfptr}
   4	| abstract_a_data
  	+---
  AbstractA::$vftable@:
  	| &AbstractA_meta
  	|  0
   0	| &AbstractA::{dtor}
   1	| &AbstractA::abstract_a_foo
   2	| &AbstractA::access
  AbstractA::{dtor} this adjustor: 0
  AbstractA::abstract_a_foo this adjustor: 0
  AbstractA::access this adjustor: 0
  AbstractA::__delDtor this adjustor: 0
  AbstractA::__vecDelDtor this adjustor: 0
  class std::is_lvalue_reference<class std::basic_ostream<char,struct std::char_traits<char> > &>	size(1):
  	+---
   0	| +--- (base class std::integral_constant<bool,1>)
  	| +---
  	+---
  class A	size(8):
  	+---
   0	| {vfptr}
   4	| a_data
  	+---
  A::$vftable@:
  	| &A_meta
  	|  0
   0	| &A::{dtor}
   1	| &A::access
  A::{dtor} this adjustor: 0
  A::access this adjustor: 0
  A::__delDtor this adjustor: 0
  A::__vecDelDtor this adjustor: 0
  class B	size(20):
  	+---
   0	| {vbptr}
   4	| b_data
  	+---
  8	| (vtordisp for vbase A)
  	+--- (virtual base A)
  12	| {vfptr}
  16	| a_data
  	+---
  B::$vbtable@:
   0	| 0
   1	| 12 (Bd(B+0)A)
  B::$vftable@:
  	| -12
   0	| &(vtordisp) B::{dtor}
   1	| &(vtordisp) B::access
  B::{dtor} this adjustor: 12
  B::access this adjustor: 12
  B::__delDtor this adjustor: 12
  B::__vecDelDtor this adjustor: 12
  vbi:	   class  offset o.vbptr  o.vbte fVtorDisp
                 A      12       0       4 1
  class C	size(20):
  	+---
   0	| {vbptr}
   4	| c_data
  	+---
  8	| (vtordisp for vbase A)
  	+--- (virtual base A)
  12	| {vfptr}
  16	| a_data
  	+---
  C::$vbtable@:
   0	| 0
   1	| 12 (Cd(C+0)A)
  C::$vftable@:
  	| -12
   0	| &(vtordisp) C::{dtor}
   1	| &(vtordisp) C::access
  C::{dtor} this adjustor: 12
  C::access this adjustor: 12
  C::__delDtor this adjustor: 12
  C::__vecDelDtor this adjustor: 12
  vbi:	   class  offset o.vbptr  o.vbte fVtorDisp
                 A      12       0       4 1
  class D	size(32):
  	+---
   0	| +--- (base class B)
   0	| | {vbptr}
   4	| | b_data
  	| +---
   8	| +--- (base class C)
   8	| | {vbptr}
  12	| | c_data
  	| +---
  16	| d_data
  	+---
  20	| (vtordisp for vbase A)
  	+--- (virtual base A)
  24	| {vfptr}
  28	| a_data
  	+---
  D::$vbtable@B@:
   0	| 0
   1	| 24 (Dd(B+0)A)
  D::$vbtable@C@:
   0	| 0
   1	| 16 (Dd(C+0)A)
  D::$vftable@:
  	| -24
   0	| &(vtordisp) D::{dtor}
   1	| &(vtordisp) D::access
  D::{dtor} this adjustor: 24
  D::access this adjustor: 24
  D::__delDtor this adjustor: 24
  D::__vecDelDtor this adjustor: 24
  vbi:	   class  offset o.vbptr  o.vbte fVtorDisp
                 A      24       0       4 1
  class E	size(12):
  	+---
   0	| +--- (base class AbstractA)
   0	| | {vfptr}
   4	| | abstract_a_data
  	| +---
   8	| e_data
  	+---
  E::$vftable@:
  	| &E_meta
  	|  0
   0	| &E::{dtor}
   1	| &E::abstract_a_foo
   2	| &E::access
  E::{dtor} this adjustor: 0
  E::abstract_a_foo this adjustor: 0
  E::access this adjustor: 0
  E::__delDtor this adjustor: 0
  E::__vecDelDtor this adjustor: 0
  class F	size(20):
  	+---
   0	| {vbptr}
   4	| f_data
  	+---
  8	| (vtordisp for vbase AbstractA)
  	+--- (virtual base AbstractA)
  12	| {vfptr}
  16	| abstract_a_data
  	+---
  F::$vbtable@:
   0	| 0
   1	| 12 (Fd(F+0)AbstractA)
  F::$vftable@:
  	| -12
   0	| &(vtordisp) F::{dtor}
   1	| &(vtordisp) F::abstract_a_foo
   2	| &(vtordisp) F::access
  F::{dtor} this adjustor: 12
  F::abstract_a_foo this adjustor: 12
  F::access this adjustor: 12
  F::__delDtor this adjustor: 12
  F::__vecDelDtor this adjustor: 12
  vbi:	   class  offset o.vbptr  o.vbte fVtorDisp
         AbstractA      12       0       4 1
  class G	size(36):
  	+---
   0	| +--- (base class E)
   0	| | +--- (base class AbstractA)
   0	| | | {vfptr}
   4	| | | abstract_a_data
  	| | +---
   8	| | e_data
  	| +---
  12	| +--- (base class F)
  12	| | {vbptr}
  16	| | f_data
  	| +---
  20	| g_data
  	+---
  24	| (vtordisp for vbase AbstractA)
  	+--- (virtual base AbstractA)
  28	| {vfptr}
  32	| abstract_a_data
  	+---
  G::$vftable@E@:
  	| &G_meta
  	|  0
   0	| &G::{dtor}
   1	| &E::abstract_a_foo
   2	| &G::access
  G::$vbtable@:
   0	| 0
   1	| 16 (Gd(F+0)AbstractA)
  G::$vftable@F@:
  	| -28
   0	| &(vtordisp) thunk: this-=28; goto G::{dtor}
   1	| &(vtordisp) thunk: this-=4; goto F::abstract_a_foo
   2	| &(vtordisp) thunk: this-=28; goto G::access
  G::{dtor} this adjustor: 0
  G::access this adjustor: 0
  G::__delDtor this adjustor: 0
  G::__vecDelDtor this adjustor: 0
  vbi:	   class  offset o.vbptr  o.vbte fVtorDisp
         AbstractA      28      12       4 1
  class H	size(44):
  	+---
   0	| {vbptr}
   4	| h_data
  	+---
  8	| (vtordisp for vbase E)
  	+--- (virtual base E)
  12	| +--- (base class AbstractA)
  12	| | {vfptr}
  16	| | abstract_a_data
  	| +---
  20	| e_data
  	+---
  24	| (vtordisp for vbase AbstractA)
  	+--- (virtual base AbstractA)
  28	| {vfptr}
  32	| abstract_a_data
  	+---
  	+--- (virtual base F)
  36	| {vbptr}
  40	| f_data
  	+---
  H::$vbtable@H@:
   0	| 0
   1	| 12 (Hd(H+0)E)
   2	| 28 (Hd(H+0)AbstractA)
   3	| 36 (Hd(H+0)F)
  H::$vftable@E@:
  	| -12
   0	| &(vtordisp) H::{dtor}
   1	| &E::abstract_a_foo
   2	| &(vtordisp) H::access
  H::$vftable@F@:
  	| -28
   0	| &(vtordisp) thunk: this-=16; goto H::{dtor}
   1	| &(vtordispex) thunk: this+=20; goto F::abstract_a_foo
   2	| &(vtordisp) thunk: this-=16; goto H::access
  H::$vbtable@F@:
   0	| 0
   1	| -8 (Hd(F+0)AbstractA)
  H::{dtor} this adjustor: 12
  H::access this adjustor: 12
  H::__delDtor this adjustor: 12
  H::__vecDelDtor this adjustor: 12
  vbi:	   class  offset o.vbptr  o.vbte fVtorDisp
                 E      12       0       4 1
         AbstractA      28       0       8 1
                 F      36       0      12 0
```

**Comment by 0xBEEEF** [comment]
Another very stupid question about VBTables in general.

Are they actually fully considered? In many of my tests where they existed, they were obviously not detected at all. All VBTables were recognized and declared as normal members (mbr_xyz) in the structures, as in the example above.

So I wonder if they are analyzed at all and if they are taken into account in the processing.

**Comment by sei-eschwartz** [comment]
Most (all?) of our VBTable information comes from RTTI.  So they should be found, but it could be related to the RTTI error you were getting in the other issue.

**Comment by cfcohen** [comment]
We will look for VBTables as well as VFTables, even without the assistance of RTTI.   The relevant code can be found here:
https://github.com/cmu-sei/pharos/blob/master/libpharos/ooanalyzer.cpp#L754
https://github.com/cmu-sei/pharos/blob/master/libpharos/ooanalyzer.cpp#L687
https://github.com/cmu-sei/pharos/blob/master/libpharos/vftable.cpp#L1

The general heuristic is to look for instructions of the form "mov [ecx+offset], constant" and then analyze the values at the constant address to see if they "look like" VFTables or VBTables.  The tricky part has been that while virtual _function_ tables can be validated based on pointing to functions, the VBTables are really just collections of smallish integers that are very difficult to validate.   It's entirely possible that our heuristics are too constraining or that we have some other defect in our logic that is preventing legitimate VBTables from being detected correctly.   There's a fair number of debugging messages in vftable.cpp, so if a particular table is missing you should be able to turn up the logging verbosity in OOAnalyzer and sort through the messages to determine where things went wrong.   I'll try to do that if I have the time, but things have been pretty busy lately.

**Comment by 0xBEEEF** [comment]
Thanks for the clarification, I couldn't have searched the complete source code so fast for the affected places!

I am well aware that the VBTables are no walk in the park. What is also important here can be seen in the Visual C++ output above.

There are also displacements of the this pointer, which makes the analysis even more difficult. 

```
  H::$vftable@F@:
  	| -28
   0	| &(vtordisp) thunk: this-=16; goto H::{dtor}
   1	| &(vtordispex) thunk: this+=20; goto F::abstract_a_foo
   2	| &(vtordisp) thunk: this-=16; goto H::access
```

But parts of this information should be found in the RTTI data. The not existing documentation of the RTTI infos doesn't make it easier either .

**Comment by sei-ccohen** [comment]
As with the other issue, this problem appears to be caused by inlining.   Unlike the other issue where we're still looking for the root cause, for the VBTables, I'm reasonably confident that the fix is commenting out these [two lines](https://github.com/cmu-sei/pharos/blob/master/share/prolog/oorules/initial.pl#L132) in initial.pl.   We're going to conduct some more tests before committing this change because it's unclear how weakening this rule might affect other cases, but it's on the right track at the very least.

**Comment by 0xBEEEF** [comment]
That sounds good! I'm sorry for trying these contrived cases. I made the settings for the creation based on files I analyzed for fun. In other words, all my examples that I analyzed had (unfortunately) a lot of inlining. This was used quite often, at least in all examples based on Visual C++. I basically agree with you that this makes the analysis much more difficult. I wish nobody would work with something like this in practice. But with all the optimizations that are done on the side, I personally feel that the analysis is hell anyway. Your tool is already a great help. A lot of time would have passed before you would have created all this manually in Ghidra, or found out about it.

**Comment by 0xBEEEF** [comment]
I have to come back to this topic again. Has the solution been found here in the meantime, or what is the state of affairs here? The problem with the inlining seems to have been solved. Here we were talking about the topic VBTables. I am just too curious about the current state of affairs.

**Comment by sei-ccohen** [comment]
There's no significant OOAnalyzer code that isn't public for sure.   My primary problem is keeping track of exactly what each ticket is tracking since they all tend to blur together a little, and evolve as the conversation progresses.  I would certainly welcome an update from you on what's still wrong in the test case (if anything).  I'm fairly certain that sei-eschwartz has run it recently, but it's a bigger question of whether it's correct in general.  Perhaps open a new ticket, if the problems have changed?

**Comment by sei-eschwartz** [comment]
I have not rerun this case recently, only the one in #131.  It is on my todo list to see if any of our recent changes have improved matters on this binary.  I would also welcome an update if you could help with that analysis @0xBEEEF.

**Comment by 0xBEEEF** [comment]
Thanks for the answers! I will let it run again at the next opportunity. But it may take a little while until I get to test it.
